//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonAuta.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoSalonEntities : DbContext
    {
        public AutoSalonEntities()
            : base("name=AutoSalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dijelovi> Dijelovi { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<Kupci> Kupci { get; set; }
        public virtual DbSet<Kvarovi> Kvarovi { get; set; }
        public virtual DbSet<Modeli> Modeli { get; set; }
        public virtual DbSet<NaciniPlacanja> NaciniPlacanja { get; set; }
        public virtual DbSet<Notifikacija> Notifikacija { get; set; }
        public virtual DbSet<Pitanja> Pitanja { get; set; }
        public virtual DbSet<Proizvodjaci> Proizvodjaci { get; set; }
        public virtual DbSet<Racuni> Racuni { get; set; }
        public virtual DbSet<RacuniStavke> RacuniStavke { get; set; }
        public virtual DbSet<SalonAuta> SalonAuta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vozila> Vozila { get; set; }
    }
}
