//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonAuta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonAuta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalonAuta()
        {
            this.Korisnici = new HashSet<Korisnici>();
        }
    
        public int SalonID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Sjedište { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korisnici> Korisnici { get; set; }
    }
}
